version: 2
jobs:
  build:
    docker:
      - image: tjmaynes/career-builder:latest
    working_directory: ~/career
    steps:
      - checkout
      - run:
          name: Build Career artifacts
          command: make build
      - persist_to_workspace:
          root: ~/career
          paths:
            - build/*
            - .git/*
  publish:
    docker:
      - image: node:8.10.0
    working_directory: ~/career
    environment:
      GIT_USERNAME: tjmaynes-bot
      GIT_EMAIL: tjmaynes+bot@gmail.com
      GIT_COMMIT_SHA: ${CIRCLE_SHA1}
    steps:
      - checkout
      - attach_workspace:
          at: ~/career
      - run:
          name: Deploy artifact to release branch
          command: make deploy_artifact
workflows:
  version: 2
  deploy_career:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - publish:
          requires:
            - build
          filters:
            branches:
              only: main