name: CI
on:
  push:
    branches:
      - '*'
      - '!release'
jobs:
  ship_it:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile CV document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
      - name: Compile resume document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
      - name: ⏰ Bump version and push tag ⏰
        uses: anothrNick/github-tag-action@master
        id: tag-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: tjmaynes
          WITH_V: true
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.tag-action.outputs.tag }}
          prerelease: false
          files: |
            LICENSE
            *.pdf
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            LICENSE
            *.pdf
